services:
  - type: web
    name: museo-embriologia
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://embryopass_user:qJLKqcQhx4TzqOga9ZkbmIiu866AUfmC@dpg-d0epejmmcj7s7382lq20-a.oregon-postgres.render.com/embryopass
